### ISSUE TITLE
Doesn't work simultaneously

### ISSUE THREAD

**Issue by otantizma** [ceremcem/aktos-dcs#4]
When i run this program at two terminals at the same time; they dont get each others messages. I have to wait before running the second program.

    from aktos_dcs import Actor,  ProxyActor, sleep, joinall
    from aktos_dcs import gevent_actor
    from aktos_dcs.Messages import *

    class Viewer(Actor):
        def handle_Inform(self, msg):
            print msg.ida +"\'s position is " + str(msg.position)
            sleep(2)

    class Player(Actor):
        def __init__(self,ID,pos):
            Actor.__init__(self)
            self.info = str(ID)
            self.position = int(pos)

        def move(self,newPos):
            self.position = int(newPos)
            self.send(Inform(ida = self.info,position = self.position))

        def getKey(self):
            pressedKey = "left"
            if pressedKey == "left":
                Player.move(self,self.position-1)

        def action(self):
            while True:
                Player.getKey(self)
                sleep(2)

    if __name__ == "__main__":
        ProxyActor()
        thisViewer = Viewer()
        playerida = input("whats your id")
        thisPlayer=Player(playerida,5)
        thisPlayer.join()
        thisViewer.join()

**Comment by ceremcem** [comment]
Should work without problems now. Pull a recent version and see if it works for you.
